In [4]:
from base_import import *

In [48]:
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import \
                                            ( LinearDiscriminantAnalysis as LDA ,
                                            QuadraticDiscriminantAnalysis as QDA)
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [6]:
df = pd.read_csv('Data/Heart_disease.csv')

In [9]:
df.columns

Index(['male', 'age', 'education', 'currentSmoker', 'cigsPerDay', 'BPMeds',
       'prevalentStroke', 'prevalentHyp', 'diabetes', 'totChol', 'sysBP',
       'diaBP', 'BMI', 'heartRate', 'glucose', 'TenYearCHD'],
      dtype='object')

In [8]:
df.rename(columns = {'TenYearCHD': 'Heart_disease'}, inplace = True)
X = df[['sysBP']]
y = df['Heart_disease']

In [11]:
df

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,Heart_disease
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4235,0,48,2.0,1,20.0,NaN,0,0,0,248.0,131.0,72.0,22.00,84.0,86.0,0
4236,0,44,1.0,1,15.0,0.0,0,0,0,210.0,126.5,87.0,19.16,86.0,NaN,0
4237,0,52,2.0,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.0,0
4238,1,40,3.0,0,0.0,0.0,0,1,0,185.0,141.0,98.0,25.60,67.0,72.0,0
4239,0,39,3.0,1,30.0,0.0,0,0,0,196.0,133.0,86.0,20.91,85.0,80.0,0

In [13]:
logistic = LogisticRegression()

X = df[['sysBP']]
y = df['Heart_disease']

logistic.fit(X, y)

LogisticRegression()

In [14]:
logistic.coef_

array([[0.02405823]])

In [17]:
logistic.intercept_

array([-5.00016447])

In [ ]:
# LogisticRegression

In [1]:
from ISLP import load_data
from ISLP.models import ( ModelSpec as MS , summarize )

In [2]:
from ISLP import confusion_table
from ISLP.models import contrast

In [17]:
X = df['totChol']

In [22]:
mask = np.isnan(X.values)
y_mask = y[~mask]
X_mask = X[~mask]

In [26]:
X_mask = pd.DataFrame(X_mask)

In [27]:
#allvars = Smarket.columns.drop (['Today ', 'Direction ', 'Year '])
design = MS(X_mask)
X_mask = design.fit_transform (X_mask)

glm = sm.GLM(y_mask, X_mask, family=sm.families.Binomial())
results = glm.fit()
summarize(results)

             coef  std err       z  P>|z|
intercept -2.8942    0.230 -12.607    0.0
totChol    0.0049    0.001   5.268    0.0

In [28]:
y_mask

0       0
1       0
2       0
3       1
4       0
       ..
4235    0
4236    0
4237    0
4238    0
4239    0
Name: Heart_disease, Length: 4190, dtype: int64

In [29]:
prob = results.predict(X_mask) 
labels = np.zeros(len(X_mask))
labels[prob > 0.5] = 1

In [33]:
y_mask

0       0
1       0
2       0
3       1
4       0
       ..
4235    0
4236    0
4237    0
4238    0
4239    0
Name: Heart_disease, Length: 4190, dtype: int64

In [35]:
confusion_table(labels ,  y_mask.values).T

Predicted     0  1
Truth
0          3554  1
1           634  1

In [36]:
3555/(3554+1+1+634)

0.8484486873508353

In [37]:
X = df['heartRate']

np.int64(1)

In [44]:
mask = np.isnan(X.values)
y_mask = y[~mask]
X_mask = X[~mask]
X_mask = pd.DataFrame(X_mask)

#allvars = Smarket.columns.drop (['Today ', 'Direction ', 'Year '])
design = MS(X_mask)
X_mask = design.fit_transform (X_mask)

glm = sm.GLM(y_mask, X_mask, family=sm.families.Binomial())
results = glm.fit()
summarize(results)

prob = results.predict(X_mask) 
labels = np.zeros(len(X_mask))
labels[prob > 0.5] = 1
summarize(results)

             coef  std err      z  P>|z|
intercept -2.1203    0.272 -7.799  0.000
heartRate  0.0052    0.004  1.491  0.136

In [45]:
confusion_table(labels ,  y_mask.values).T

Predicted     0  1
Truth
0          3596  0
1           643  0

In [47]:
3596/(643+3596)

0.8483132814343005

In [50]:
spam_email_df = pd.read_csv('Data/spam_train.csv')

In [52]:
y = spam_email_df['y']
X = spam_email_df.drop('y', axis = 1)

In [58]:
def perform_logistic_regression(X, y, summary = None):

    design = MS(X)
    X = design.fit_transform(X)
    glm = sm.GLM(y, 
                 X,
                 family=sm.families.Binomial ())
    results = glm.fit()

    if summary:
        print(summarize(results))

        
    return results

In [59]:
results = perform_logistic_regression(X, y, summary= True)

                              coef  std err       z  P>|z|
intercept                  -2.2381    0.109 -20.549  0.000
word.freq.remove            5.7161    0.560  10.199  0.000
word.freq.order             0.9169    0.213   4.311  0.000
word.freq.free              1.1018    0.139   7.907  0.000
word.freq.meeting          -3.9107    1.094  -3.573  0.000
word.freq.re               -0.3800    0.109  -3.499  0.000
word.freq.edu              -1.2632    0.256  -4.934  0.000
char.freq.semicolon        -1.6941    0.669  -2.531  0.011
char.freq.exclamation       2.2251    0.187  11.901  0.000
capital.run.length.average  0.3421    0.032  10.570  0.000

In [60]:
np.exp(5.7161)

np.float64(303.71810954781)

In [61]:
np.exp(-1.6941 )

np.float64(0.18376454271384293)

In [64]:
prob = results.predict() 
labels = np.zeros(len(X))
labels[prob > 0.5] = 1
confusion_table(labels ,  y).T
#summarize(results)

Predicted     0    1
Truth
0          1703   97
1           321  879

In [72]:
(1703+879)/(1703+879+321+97)

0.8606666666666667

In [65]:
X = spam_email_df.drop(['y', 'word.freq.meeting', 'word.freq.re', 'char.freq.semicolon'], axis = 1)

In [69]:
result_removed = perform_logistic_regression(X, y, summary= True)

                              coef  std err       z  P>|z|
intercept                  -2.4422    0.103 -23.675    0.0
word.freq.remove            6.1240    0.570  10.735    0.0
word.freq.order             1.0906    0.214   5.096    0.0
word.freq.free              1.1440    0.133   8.604    0.0
word.freq.edu              -1.3359    0.261  -5.125    0.0
char.freq.exclamation       2.2407    0.176  12.744    0.0
capital.run.length.average  0.3190    0.030  10.801    0.0

In [70]:
prob = result_removed.predict() 
labels = np.zeros(len(X))
labels[prob > 0.5] = 1
confusion_table(labels ,  y).T
#summarize(results)

Predicted     0    1
Truth
0          1696  104
1           338  862

In [71]:
(1696+862)/(1696+862+  338+  104)

0.8526666666666667